### ISSUE TITLE
v1.0 contains duplicate operationIds

### ISSUE THREAD

**Issue by MikeRalphson** [microsoftgraph/microsoft-graph-openapi#9]
```
Gathering...
GET https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-openapi/master/v1.0.json
https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-openapi/master/v1.0.json
#/paths/~1deviceAppManagement~1managedAppRegistrations~1{managedAppRegistration-id}~1appliedPolicies~1{managedAppPolicy-id}~1targetApps/post
operationIds must be unique [deviceAppManagement.deviceAppManagement.targetApps]
  OData Service for namespace microsoft.graph 1.0.1
  https://graph.microsoft.com/v1.0 

Failures:
https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-openapi/master/v1.0.json
```

**Comment by MikeRalphson** [comment]
There also appear to be some duplicated parameters:

```yaml
  '/groups/{group-id}/calendar/calendarView/{event-id}/instances/{event-id}':
    get:
      operationId: groups.calendar.calendarView.GetInstances
      parameters:
        - description: 'key: group-id'
          in: path
          name: group-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: group
        - description: 'key: event-id'
          in: path
          name: event-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: event
        - description: 'key: event-id'
          in: path
          name: event-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: event
```
